# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner  # No dynamic provisioning
# volumeBindingMode: WaitForFirstConsumer    # Binds PV to a node only when a pod is scheduled

