apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mbenguosta/backend:v4.0.0
          ports:
            - containerPort: 8000
          env:
            # - name: MONGO_URI
            #   valueFrom:
            #     configMapKeyRef:
            #       name: backend-config
            #       key: MONGO_URI
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: DATABASE_HOST
              value: mongodb
            - name: DATABASE_PORT
              value: "27017"

