apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
      #     volumeMounts:
      #       - name: mongodb-storage
      #         mountPath: /data/db   # Default MongoDB data directory
      # volumes:
      #   - name: mongodb-storage
      #     persistentVolumeClaim:
      #       claimName: mongodb-pvc   # PVC defined earlier
