repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - "markdown"
        - tfvars hcl --output-file terraform.tfvars.model .
        - "README.md"
        - "inject"
        - --args=--config=.terraform-docs.yml
      types: [terraform]

#    - id: terraform_trivy
#      files: ^Cloud/Terraform/modules/vm
