apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80

        livenessProbe:
          httpGet:
            path: /healthz   
            port: 80          
          initialDelaySeconds: 10  
          periodSeconds: 5        
          timeoutSeconds: 5        
          failureThreshold: 3       
          successThreshold: 1      

        readinessProbe:
          httpGet:
            path: /ready    
            port: 80
          initialDelaySeconds: 5    
          periodSeconds: 5         
          timeoutSeconds: 3         
          failureThreshold: 3       
          successThreshold: 1       

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
